package org.ipr.giftsproducer.service;

import lombok.Getter;

import java.util.List;

public class GiftParts {
    @Getter
    private static final List<String> toys = List.of(
            "Toy Car",
            "Water Pistol",
            "Barbie Doll",
            "LEGO Set",
            "Action Figures",
            "Remote Control Car",
            "Play-Doh Set",
            "Puzzle",
            "Board Game",
            "Stuffed Animal",
            "Building Blocks",
            "Art Supplies",
            "Science Kit",
            "Dollhouse",
            "Train Set",
            "Toy Kitchen",
            "Musical Instrument Toy",
            "Sports Equipment",
            "Bicycle",
            "Scooter",
            "Roller Skates",
            "Craft Kit",
            "Storybook",
            "Educational Tablet",
            "Robot Toy",
            "Magic Kit",
            "Costume Dress-Up Set",
            "Toy Tool Set",
            "Walkie Talkies",
            "Kite",
            "Telescope",
            "Microscope",
            "Gardening Kit",
            "Bath Toys",
            "Sandbox Toys",
            "Play Tent",
            "Chalk Set",
            "Toy Camera",
            "Binoculars",
            "Toy Cash Register",
            "Toy Doctor Kit",
            "Toy Pet Set",
            "Toy Garage",
            "Toy Airplane",
            "Toy Boat",
            "Toy Soldiers",
            "Toy Dinosaurs",
            "Toy Animals",
            "Toy Farm Set",
            "Toy Castle"
    );

    @Getter
    private static final List<String> toyAdjectives = List.of(
            "Red",
            "Big",
            "Shiny",
            "Cheap",
            "Colorful",
            "Small",
            "Soft",
            "Durable",
            "Fun",
            "Exciting",
            "Educational",
            "Interactive",
            "Creative",
            "Lightweight",
            "Portable",
            "Safe",
            "Bright",
            "Sparkly",
            "Cute",
            "Adorable",
            "Fancy",
            "Modern",
            "Classic",
            "Innovative",
            "Unique",
            "Popular",
            "Trendy",
            "Affordable",
            "High-quality",
            "Sturdy",
            "Flexible",
            "Versatile",
            "Engaging",
            "Entertaining",
            "Realistic",
            "Detailed",
            "Vibrant",
            "Whimsical",
            "Magical",
            "Imaginative",
            "Compact",
            "Eco-friendly",
            "Rechargeable",
            "Battery-operated",
            "Noisy",
            "Quiet",
            "Soft-touch",
            "Plush",
            "Collectible",
            "Limited-edition"
    );

}
