services:
  gift-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  child-db:
    image: postgres:latest
    container_name: child-db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=child
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    links:
      - prometheus
volumes:
  grafana-storage:

#  gifts-service:
#    image: alpine
#    ports:
#      - "8081:8081"
#    entrypoint:
#      - DRIVER_NAME=org.postgresql.Driver
#      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/child
#      - DATASOURCE_USER=admin
#      - DATASOURCE_PASSWORD=admin

#  comments-mongo:
#    image: mongo:latest
#    environment:
#      - MONGO_PORT=27018
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root
#    ports:
#      - "27018:27018"
#  #    command: mongod --rest
#  #    networks:
#  #      - mongo-compose-network
#
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8111:8081"
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=flux-app-posts-mongo-1
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=root

#  prometheus:
#    image: prom/prometheus:v2.30.3
#    ports:
#      - 9000:9090
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prometheus_data:/prometheus
#    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml
#    container_name: prometheus
#    restart: unless-stopped
#    depends_on:
#      - mongo
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    volumes:
#      - ./grafana:/var/lib/grafana
#    restart: unless-stopped
#    ports:
#      - 3000:3000
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_SERVER_DOMAIN=localhost
#    depends_on:
#      - prometheus
#
#volumes:
#  prometheus_data:

