spring:
    application:
        name: child-hub
    r2dbc:
        url: ${DATASOURCE_URL:r2dbc:postgresql://localhost:5432/child}
        username: ${DATASOURCE_USER:admin}
        password: ${DATASOURCE_PASSWORD:admin}
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"
    elastic:
        metrics:
            export:
                enabled: true
    metrics:
        tags:
            application: ${spring.application.name}
logging:
    level:
        org:
            springframework:
                transaction: WARN
                transaction.interceptor: WARN
                data.r2dbc: INFO

        io.r2dbc.postgresql.QUERY: INFO
        io.r2dbc.postgresql.PARAM: INFO
        root: info
    file:
        name: logs/child-application.log
data.init.enabled: true
server:
  tomcat:
    enabled: false