spring:
    application:
        name: gifts-producer
    r2dbc:
        url: ${DATASOURCE_URL:r2dbc:postgresql://localhost:5432/child}
        username: ${DATASOURCE_USER:admin}
        password: ${DATASOURCE_PASSWORD:admin}
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true
                ddl_auto: update

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: "always"
    elastic:
        metrics:
            export:
                enabled: true
    metrics:
        tags:
            application: ${spring.application.name}
logging:
    level:
        org:
            springframework:
                transaction: WARN
                transaction.interceptor: WARN
                data.r2dbc: DEBUG
        #        r2dbc: DEBUG
        #
        io.r2dbc.postgresql.QUERY: DEBUG
        io.r2dbc.postgresql.PARAM: DEBUG
data.init.enabled: true
