server:
  port: 8081

spring:
  application:
    name: gifts-producer

logging:
  level:
    org:
      springframework:
        transaction: WARN
        transaction.interceptor: WARN
    root: info



